on:
  pull_request:

name: lint
permissions:
  contents: write

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
  prettier_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            markdown:
              - '**.md'
      - name: Prettify code
        if: steps.changed-files.outputs.markdown_any_changed == 'true'
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ steps.changed-files.outputs.markdown_all_changed_files }}