on:
  pull_request:

name: lint-shell
permissions:
  contents: write

jobs:
  sh:
    name: simple-shell-syntax-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Klintrup/simple-shell-syntax-check@v1
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
